const User = [
  {
    id: "user1",
    email: "user1@example.com",
    nickname: "테스트",
    image: null,
    encryptedPassword: "12345678",
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "user2",
    email: "user2@example.com",
    nickname: "유저유디",
    image: null,
    encryptedPassword: "12341234",
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "user3",
    email: "user3@example.com",
    nickname: "데이터유저",
    image: null,
    encryptedPassword: "11111111",
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "user4",
    email: "user4@example.com",
    nickname: "고양이귀여워",
    image: null,
    encryptedPassword: "00000000",
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "user5",
    email: "user5@example.com",
    nickname: "강아지귀여워",
    image: null,
    encryptedPassword: "45678901",
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default User;
